### ISSUE TITLE
Please Help: Hx300 getting error.

### ISSUE THREAD

**Issue by amitpandey2194** [ma1co/fwtool.py#25]
Querying MTP device
Sony Corporation DSC-HX300 is a camera in MTP mode

Model:              DSC-HX300
Product code:       0080813110
Serial number:      04520210
Firmware version:   1.00

Using drivers Windows-MSC, Windows-MTP
Looking for Sony devices

Querying MTP device
Sony Corporation DSC-HX300 is a camera in MTP mode

Switching to app install mode
Traceback (most recent call last):
  File "C:\projects\sony-pmca-re\pmca-gui.py", line 76, in do
  File "C:\projects\sony-pmca-re\pmca\commands\usb.py", line 274, in installCommand
  File "C:\projects\sony-pmca-re\pmca\commands\usb.py", line 37, in switchToAppInstaller
  File "C:\projects\sony-pmca-re\pmca\usb\sony.py", line 306, in switchToAppInstaller
  File "C:\projects\sony-pmca-re\pmca\usb\sony.py", line 244, in _sendCommand
  File "C:\projects\sony-pmca-re\pmca\usb\sony.py", line 98, in sendSonyExtCommand
  File "C:\projects\sony-pmca-re\pmca\usb\__init__.py", line 81, in _checkResponse
pmca.usb.InvalidCommandException: MTP error 0x2006

**Comment by amitpandey2194** [comment]
I tried both MTP as well Mass Storage option on the camera

**Comment by ma1co** [comment]
This camera does not support apps. Please use updatershell / serviceshell instead.
