### ISSUE TITLE
Sony A9 have new firmware.dat

### ISSUE THREAD

**Issue by NetrunnerAT** [ma1co/fwtool.py#3]
URL to File -> http://support.d-imaging.sony.co.jp/download/NEX/7DdvKguuiL/Update_ILCE9V101.exe?fm=na

Error MSG:

Extracting installer binary
Decrypting firmware image
Traceback (most recent call last):
  File "<string>", line 228, in <module>
  File "<string>", line 218, in main
  File "<string>", line 127, in unpackCommand
  File "<string>", line 83, in unpackDat
  File "fwtool\sony\fdat.py", line 213, in decryptFdat
Exception: No decrypter found
fwtool returned -1

**Comment by ma1co** [comment]
This is now supported (decryption only).
