### ISSUE TITLE
A7RM5 has new firmware (BODYDATA.DAT)

### ISSUE THREAD

**Issue by samanL33T** [ma1co/fwtool.py#45]
Hi,

The latest release fails with the decryption of latest firmware image for A7RM5. Following is the error:

$ .\fwtool-v1.2-win.exe unpack -f BODYDATA.DAT -o unpacked_sony
Decrypting firmware image
Traceback (most recent call last):
  File "<string>", line 297, in <module>
  File "<string>", line 285, in main
  File "<string>", line 167, in unpackCommand
  File "<string>", line 106, in unpackDat
  File "fwtool\sony\fdat.py", line 214, in decryptFdat
Exception: No decrypter found
fwtool returned -1

**Comment by gbkwiatt** [comment]
So is it possible to get a support for that ? How do you even obtain those  decrypt keys ?

**Comment by DavidBuchanan314** [comment]
Implemented in https://github.com/ma1co/fwtool.py/pull/52
