### ISSUE TITLE
"KeyError: '_winzip_' fwtool returned -1" when attempting to unpack firmware

### ISSUE THREAD

**Issue by RobotToaster** [ma1co/fwtool.py#46]
When trying to unpack a Sony A7 firmware on windows 10 I get the following error:

```
PS C:\Users\xxxx\Documents\sonytest> .\fwtool-v1.2-win.exe unpack -f Update_ILCE7V320.exe -o outDir
Extracting installer binary
Traceback (most recent call last):
  File "<string>", line 297, in <module>
  File "<string>", line 285, in main
  File "<string>", line 162, in unpackCommand
  File "<string>", line 94, in unpackInstaller
KeyError: '_winzip_'
fwtool returned -1
```

Is this a bug? or is there something I can do to fix this?

**Comment by DukeTomlist** [comment]
I also encountered such a problem. I think fwtool is not able to handle .exe file format.
However, you can unpack the firmware as bellow:
1. Use the Telnet and dump the firmware to the SD card  (android 4 for example):
```dd if=/dev/nflasha of=/android/storage/sdcard0/DUMP.DAT bs=1M```
2. Use the fwtool to unpack the .dat file:
```fwtool unpack -f XXX.dat -o outDir```

Hoping this will be helpful to you

**Comment by ma3rian** [comment]
hi !

i tried to unpack the latest fw for sony ILCE7M3 (4.01) and i get the following error:

Decrypting firmware image
Traceback (most recent call last):
  File "<string>", line 297, in <module>
  File "<string>", line 285, in main
  File "<string>", line 167, in unpackCommand
  File "<string>", line 106, in unpackDat
  File "fwtool\sony\fdat.py", line 214, in decryptFdat
Exception: No decrypter found
fwtool returned -1

does anyone knows why is this happening?

**Comment by nixcamic** [comment]
Or download the macOS updater, open it in 7-zip to: Update_ILCE7V320.dmg\Update_ILCE7V320\FirmwareUpdater.app\Contents\Resources and extract the file FirmwareData_ILCE7V320.dat then run fwtool on that.

**Comment by workfriend** [comment]
> Or download the macOS updater, open it in 7-zip to: Update_ILCE7V320.dmg\Update_ILCE7V320\FirmwareUpdater.app\Contents\Resources and extract the file FirmwareData_ILCE7V320.dat then run fwtool on that.

This absolutely works.

I was trying to figure out the a7ii's firmware, and your instructions helped.

I'll provide my example of what can be expected.

```
$ ./fwtool unpack -f /Volumes/Update_ILCE7M2V401/Resources/SystemSoftwareUpdater.app/Contents/Resources/FirmwareData_ILCE7M2V401.dat -o /Volumes/ExtHDD/Downloads/FirmwareTest
Decrypting firmware image
Extracting files
Unpacking /Volumes/ExtHDD/Downloads/FirmwareTest/firmware.tar
Unpacking /Volumes/ExtHDD/Downloads/FirmwareTest/firmware.tar_unpacked/0700_part_image/dev/nflasha15
Unpacking /Volumes/ExtHDD/Downloads/FirmwareTest/firmware.tar_unpacked/0700_part_image/dev/nflasha15_unpacked
Unpacking /Volumes/ExtHDD/Downloads/FirmwareTest/firmware.tar_unpacked/0700_part_image/dev/nflasha15_unpacked_unpacked/bin/ramdisk.img
Unpacking /Volumes/ExtHDD/Downloads/FirmwareTest/firmware.tar_unpacked/0700_part_image/dev/nflasha15_unpacked_unpacked/bin/ramdisk.img_unpacked
Unpacking /Volumes/ExtHDD/Downloads/FirmwareTest/firmware.tar_unpacked/0700_part_image/dev/nflasha15_unpacked_unpacked/bin/udtrbody.bin
Unpacking /Volumes/ExtHDD/Downloads/FirmwareTest/firmware.tar_unpacked/0700_part_image/dev/nflasha16
Unpacking /Volumes/ExtHDD/Downloads/FirmwareTest/firmware.tar_unpacked/0700_part_image/dev/nflasha16_unpacked
Unpacking /Volumes/ExtHDD/Downloads/FirmwareTest/firmware.tar_unpacked/0700_part_image/dev/nflasha16_unpacked_unpacked/etc/NOTICE.html.gz
Unpacking /Volumes/ExtHDD/Downloads/FirmwareTest/firmware.tar_unpacked/0700_part_image/dev/nflasha3
Unpacking /Volumes/ExtHDD/Downloads/FirmwareTest/firmware.tar_unpacked/0700_part_image/dev/nflasha3_unpacked
Unpacking /Volumes/ExtHDD/Downloads/FirmwareTest/firmware.tar_unpacked/0700_part_image/dev/nflasha3_unpacked_unpacked/initrd.img
Unpacking /Volumes/ExtHDD/Downloads/FirmwareTest/firmware.tar_unpacked/0700_part_image/dev/nflasha7
Unpacking /Volumes/ExtHDD/Downloads/FirmwareTest/firmware.tar_unpacked/0700_part_image/dev/nflasha7_unpacked
Unpacking /Volumes/ExtHDD/Downloads/FirmwareTest/updater.img
```
